# -------------------------------
# Deployment de alpine
# -------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: alpine-app
  template:
    metadata:
      labels:
        app: alpine-app
    spec:
      containers:
        - image: alpine:latest
          name: alpine-app
          command: ["sh", "-c", "while true; do sleep 3600; done"]
          ports:
            - containerPort: 80
---
# -------------------------------
# Service para alpine
# -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: alpine-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: alpine-app
---
# -------------------------------
# PostSync Hook para ejecutar curl DAST
# -------------------------------
apiVersion: batch/v1
kind: Job
metadata:
  name: run-dast-scan
  annotations:
    argocd.argoproj.io/hook: PostSync
    # No eliminar el Job automáticamente para depuración
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  template:
    spec:
      containers:
        - name: trigger-dast
          image: curlimages/curl:latest
          command:
            - "sh"
            - "-c"
            - >
              echo "Ejecutando DAST scan..." &&
              curl -v -k -X POST "https://dastapi.otlatam.com:6443/api/v2/scans/start-scan-cicd"
              -H "Authorization: FORTIFYTOKEN ZTBiZDkzNmEtYzBjNC00MTk4LTg5ZDktMmM3YmM2YmI4ZDYx"
              -H "Content-Type: application/json"
              -d '{"cicdToken":"144ecc72-3cc4-49d2-b353-a1c5f3dd0c19","name":"Pruebasargocd","scannerId":0,"useAssignedScannerOnly":true}' \
              2>&1 | tee /tmp/dast.log
      restartPolicy: Never
  backoffLimit: 0
