# -----------------------------------
# 1. Deployment simple
# -----------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-service
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
        - name: my-service
          image: nginx:latest
          ports:
            - containerPort: 80
---
# -----------------------------------
# 2. Service
# -----------------------------------
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-service
---
# -----------------------------------
# 3. PostSync Job que ejecuta CURL
# -----------------------------------
apiVersion: batch/v1
kind: Job
metadata:
  name: dast-scan-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: curl-trigger
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              echo "Agregando host manual al /etc/hosts..."
              echo "192.168.41.185 dastapi.otlatam.com" >> /etc/hosts

              echo "Ejecutando el CURL hacia DAST..."
              curl -k -X POST "https://dastapi.otlatam.com:6443/api/v2/scans/start-scan-cicd" \
                -H "Authorization: FORTIFYTOKEN ZTBiZDkzNmEtYzBjNC00MTk4LTg5ZDktMmM3YmM2YmI4ZDYx" \
                -H "Content-Type: application/json" \
                -d '{"cicdToken":"144ecc72-3cc4-49d2-b353-a1c5f3dd0c19","name":"Prueba
